Removed after show trigger call, this call was directing the focus to…
nextcloud-libraries/nextcloud-vue pull request #2736
Opened 2022-06-07 10:18 UTC by mstolf

Removed after show trigger call, this call was directing the focus to the div of the DotsHorizontal component, making that when clicking outside the component the "..." appear again

Fix [#7459](https://github.com/nextcloud/spreed/issues/7459)

2022-11-17 07:25 UTC, skjnldsv commented
Can you rebase @mstolf  :)

2023-03-24 11:04 UTC, juliushaertl requested changes

2023-03-24 11:04 UTC, juliushaertl commented on src/components/Avatar/Avatar.vue
> -			// bring focus back to the trigger
This is still a case that should be preserved when closing the menu with the keyboard I guess. This was introduced with https://github.com/nextcloud/nextcloud-vue/pull/1854 for accessibility reasons.

2024-02-29 13:53 UTC, susnux commented
Is this still relevant?

2024-08-30 12:07 UTC, susnux commented
Closing as there is no activity for two years.
If this is still relevant please reopen the PR.

2024-08-30 12:07 UTC, closed without merging