NcModal's left column width increase for french and other "large words" languages
nextcloud-libraries/nextcloud-vue pull request #3829
Opened 2023-02-27 13:55 UTC by Jerome-Herbinet

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

NcModal width increase to compensate NcModal's left column width increase.

Some examples for too thing left column in French : 

![2023-02-27_14-47](https://user-images.githubusercontent.com/33763786/221582042-a07f8303-8638-4773-89b2-27c85f0aca98.png)

![2023-02-27_14-45](https://user-images.githubusercontent.com/33763786/221582069-20d60359-c17e-4144-b590-2c32e099d268.png)

2023-03-02 10:02 UTC, raimund-schluessler commented
@Jerome-Herbinet Can you please remove the changes to `package-lock.json`?

2023-03-02 10:56 UTC, nimishavijay commented
Good observation! Checking the width, increasing the left column 300px leaves a lot of space to the right, at least when the language is set to English. Does this PR affect the width for all languages? If yes, then we can go with a smaller number like 256px. If this affects only certain languages then it is all good! :)

<img src="https://user-images.githubusercontent.com/52440189/222408557-62ad5f92-253c-49d7-a8fc-1a46d89870d2.png" width=75% height=75%)>

2023-03-02 11:09 UTC, raimund-schluessler commented
It affects all languages.

2023-03-02 11:26 UTC, jancborchardt reviewed
Would an increase by 50px also be enough? And the additional modal width increase I’d say we leave out?

cc modal & navigation pro @marcoambrosini

2023-03-02 12:21 UTC, marcoambrosini commented
How about we make this fullscreen??

2023-03-02 13:47 UTC, Jerome-Herbinet commented
@jancborchardt, I tested with only 50px before doing the PR, and IMO, it's not enough ...
But, as @jancborchardt says, we can leave the main modal with unchanged, why not. 
I'm waiting for your instructions.
@raimund-schluessler, I'll remove the mentioned file.

2023-03-02 14:23 UTC, Jerome-Herbinet commented
OK @raimund-schluessler ; file deleted with a rebase.

2023-03-15 14:09 UTC, Jerome-Herbinet commented
Are you finally waiting for me to do a test with different widths ?

2023-03-15 16:55 UTC, marcoambrosini commented
I think that settings are so complex that they deserve the entire screen. There's really no need to truncate anything in my opinion and I can't think of any benefit in showing other parts of the app interface while changing the settings, it's just a distraction. 

https://user-images.githubusercontent.com/26852655/225382948-db9e4c83-0da9-4728-9f2c-d984efcc994d.mov

2023-03-17 13:33 UTC, marcoambrosini requested changes
After testing it with @nimishavijay we decided that we could go with `400px` for the navigation, which collapses when `isMobile` is true. The width of the content was already too much anyway

2023-03-17 13:33 UTC, marcoambrosini commented on src/components/NcModal/NcModal.vue
> +			width: 1000px;
```suggestion
			width: 900px;
```

2023-03-17 13:33 UTC, marcoambrosini commented on src/components/NcAppSettingsDialog/NcAppSettingsDialog.vue
> +		min-width: 300px;
```suggestion
		min-width: 400px;
```

2023-03-20 10:09 UTC, Jerome-Herbinet commented
> After testing it with @nimishavijay we decided that we could go with `400px` for the navigation, which collapses when `isMobile` is true. The width of the content was already too much anyway

Done

2023-03-22 12:47 UTC, marcoambrosini approved these changes

2023-03-22 13:29 UTC, Jerome-Herbinet commented
> > Done
> 
> Nice! @Jerome-Herbinet could you please post updated screenshots so it's easier for everyone to review? :)

Hi @nimishavijay, below is the before and after display. 
**However**, I don't understand one thing after accepting @marcoambrosini's changes.
I have, in the "Files changed" tab only the NcAppSettingsDialog.vue file, while there was also the NcModal.vue file changed (missing). Can you tell me what's going on ? Did I forget to do something, or did I do it wrong?

Before : 
![2023-03-22_14-02](https://user-images.githubusercontent.com/33763786/226918197-55263c22-0709-4676-a2f3-6ed480a48288.png)

After : 
![2023-03-22_14-24](https://user-images.githubusercontent.com/33763786/226918215-dd93c187-af57-4cfc-9df8-511f8ed58942.png)

2023-05-15 10:10 UTC, jancborchardt requested changes
> After testing it with @nimishavijay we decided that we could go with 400px for the navigation

@marcoambrosini @nimishavijay judging from the latest screenshot, this looks way unbalanced, with nav almost as wide as content.

If this is still relevant and not fixed elsewhere, something between 250 and 300px should be enough.

2023-05-15 14:56 UTC, Jerome-Herbinet commented
> > After testing it with @nimishavijay we decided that we could go with 400px for the navigation
> 
> @marcoambrosini @nimishavijay judging from the latest screenshot, this looks way unbalanced, with nav almost as wide as content.
> 
> If this is still relevant and not fixed elsewhere, something between 250 and 300px should be enough.

@jancborchardt : 
Reduced to 300px (with of the navigation left column), but, as a reminder, note that global modal width hasn't been compensated.

2023-05-15 16:28 UTC, jancborchardt commented
> Reduced to 300px (with of the navigation left column), but, as a reminder, note that global modal width hasn't been compensated.

Seems good to me. What does it mean that it needs to be compensated? cc @marcoambrosini

2023-05-15 18:11 UTC, Jerome-Herbinet commented
> > Reduced to 300px (with of the navigation left column), but, as a reminder, note that global modal width hasn't been compensated.
> 
> Seems good to me. What does it mean that it needs to be compensated? cc @marcoambrosini 

I mean that i f you enlarge the left column, after, you have less space (less width) for content. So if the original left column was 200px wide  and that its now 300px wide, we should make the modal 100px larger in order to guaranty that content keepa as much space (width) as before. What do you think ?

2023-05-19 09:07 UTC, ShGKme commented
What about making the column (and modal) optionally flexible to fit content? With hard limits. So that in any language, when applicable, the column's width would be enough for the longest option but not more.

2023-05-19 15:02 UTC, szaimen approved these changes
Just tested and 300px looks good to me :)

2023-06-12 09:08 UTC, marcoambrosini commented
@nimishavijay it's fine to ellipsize user names or email subjects but not something like setting sections. I've never seen that.  I'd advise to wrap the text regardless of the column width we choose.

2024-04-19 09:32 UTC, Jerome-Herbinet commented
I just saw that the left column is larger than before, for example in the Talk's settings modal, in Nextcloud 28. I don't think it is due to my PR because it's still not merged. Can I close it ?

2024-04-19 19:40 UTC, ShGKme commented
With new `NcDialog` design, navigation now is not limited anymore. It is as wide as needed for the widest item. Though, probably this is also an issue, because in the worth case, there is no place for content at all.

2024-04-23 07:05 UTC, Jerome-Herbinet commented
> With new `NcDialog` design, navigation now is not limited anymore. It is as wide as needed for the widest item. Though, probably this is also an issue, because in the worth case, there is no place for content at all.

Wouldn't it be possible to specify a maximum width for the left-hand column?

2024-04-23 07:15 UTC, ShGKme commented
> Wouldn't it be possible to specify a maximum width for the left-hand column?

It is possible. It's just another issue.

2024-04-29 12:11 UTC, Jerome-Herbinet commented
> > Wouldn't it be possible to specify a maximum width for the left-hand column?
> 
> It is possible. It's just another issue.

@ShGKme I made some tests and couldn't reproduce the issue that you described ; do you have any precise example (screenshot) ?

2024-04-29 12:34 UTC, Jerome-Herbinet commented
> ![image](https://private-user-images.githubusercontent.com/25978914/326433556-be9ba814-81b9-4b30-a70d-ee2604c51077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTM4NTYsIm5iZiI6MTcxNDM5MzU1NiwicGF0aCI6Ii8yNTk3ODkxNC8zMjY0MzM1NTYtYmU5YmE4MTQtODFiOS00YjMwLWE3MGQtZWUyNjA0YzUxMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDEyMjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NGQ5MjYyMmRkZWI0OWZkMzM4YWRiYTY4ZWJlNjRjMWRhNDVhY2YxMzUzNzYyNGY3YTJlNTk4MWViMTEyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgVibfp27jo56ufEstTOVUDuAeD3MnTJjWWv-Ve1gqA)

OK @ShGKme, thanks, it's clear now for me. @jancborchardt is this a bug or a feature ? 
Shouldn't we get a "max-with" coupled with an "ellipsis"  in order to avoid that ?

2024-04-29 13:44 UTC, Jerome-Herbinet commented
> > ![image](https://private-user-images.githubusercontent.com/25978914/326433556-be9ba814-81b9-4b30-a70d-ee2604c51077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTM4NTYsIm5iZiI6MTcxNDM5MzU1NiwicGF0aCI6Ii8yNTk3ODkxNC8zMjY0MzM1NTYtYmU5YmE4MTQtODFiOS00YjMwLWE3MGQtZWUyNjA0YzUxMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDEyMjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NGQ5MjYyMmRkZWI0OWZkMzM4YWRiYTY4ZWJlNjRjMWRhNDVhY2YxMzUzNzYyNGY3YTJlNTk4MWViMTEyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgVibfp27jo56ufEstTOVUDuAeD3MnTJjWWv-Ve1gqA)
> 
> OK @ShGKme, thanks, it's clear now for me. @jancborchardt is this a bug or a feature ? Shouldn't we get a "max-with" coupled with an "ellipsis" in order to avoid that ?

Not that great : 
![Capture d’écran du 2024-04-29 15-44-11](https://github.com/nextcloud-libraries/nextcloud-vue/assets/33763786/6d0481f0-4508-4d1c-93bc-be70eab36607)

2024-04-29 22:22 UTC, jancborchardt commented
> > ![image](https://private-user-images.githubusercontent.com/25978914/326433556-be9ba814-81b9-4b30-a70d-ee2604c51077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTM4NTYsIm5iZiI6MTcxNDM5MzU1NiwicGF0aCI6Ii8yNTk3ODkxNC8zMjY0MzM1NTYtYmU5YmE4MTQtODFiOS00YjMwLWE3MGQtZWUyNjA0YzUxMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDEyMjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NGQ5MjYyMmRkZWI0OWZkMzM4YWRiYTY4ZWJlNjRjMWRhNDVhY2YxMzUzNzYyNGY3YTJlNTk4MWViMTEyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgVibfp27jo56ufEstTOVUDuAeD3MnTJjWWv-Ve1gqA)
> 
> OK @ShGKme, thanks, it's clear now for me. @jancborchardt is this a bug or a feature ? 
> Shouldn't we get a "max-with" coupled with an "ellipsis"  in order to avoid that ?

Yes absolutely, otherwise the interface breaks with just 1 faulty text.

Also, texts and translations need to be kept aptly short. E.g. "Peripheriques" instead of "Choissisez les peripheriques" etc. if that works.

2024-05-23 14:06 UTC, Jerome-Herbinet commented
> > > ![image](https://private-user-images.githubusercontent.com/25978914/326433556-be9ba814-81b9-4b30-a70d-ee2604c51077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTM4NTYsIm5iZiI6MTcxNDM5MzU1NiwicGF0aCI6Ii8yNTk3ODkxNC8zMjY0MzM1NTYtYmU5YmE4MTQtODFiOS00YjMwLWE3MGQtZWUyNjA0YzUxMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDEyMjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NGQ5MjYyMmRkZWI0OWZkMzM4YWRiYTY4ZWJlNjRjMWRhNDVhY2YxMzUzNzYyNGY3YTJlNTk4MWViMTEyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgVibfp27jo56ufEstTOVUDuAeD3MnTJjWWv-Ve1gqA)
> > 
> > 
> > OK @ShGKme, thanks, it's clear now for me. @jancborchardt is this a bug or a feature ?
> > Shouldn't we get a "max-with" coupled with an "ellipsis"  in order to avoid that ?
> 
> Yes absolutely, otherwise the interface breaks with just 1 faulty text.
> 
> Also, texts and translations need to be kept aptly short. E.g. "Peripheriques" instead of "Choissisez les peripheriques" etc. if that works.

@jancborchardt can you test my last commit ?

2024-08-19 12:09 UTC, jancborchardt reviewed
Considering the overall size of the settings window and the idea that we want the wording there to be short, I would go for max-width 200px instead. Otherwise looks fine. :)

2024-08-22 13:05 UTC, Jerome-Herbinet commented
@jancborchardt ; I've taken a look at NC 27 to 30, and it seems that the problem has been fixed since NC 28 ; the left panel is larger and the modal is well sized IMO. I close this PR.

2024-08-22 13:05 UTC, closed without merging