Better readability of long file and event names
nextcloud-libraries/nextcloud-vue pull request #4194
Opened 2023-06-07 11:48 UTC by Jerome-Herbinet

Respawn of old PR https://github.com/nextcloud/nextcloud-vue/pull/3295 (which encountered a cypress problem)

Currently, on the right side panel, the labels end too easily with ellipsis dots. This is, from my personal and professional experience, too restrictive because we often cannot see the continuation of the file or event name (potentially also in any other similar case using this "vue"). It's a pain especially in Nextcloud Calendar but in Nextcloud Files too and probably in other apps.

I propose, with this change, to allow 3 lines to be displayed before the ellipsis.

**Nextcloud Calendar test :** 
![2022-09-26_16-01](https://user-images.githubusercontent.com/33763786/192299295-763d6964-dfb9-4a67-b7a6-acb0d56a2ba7.png)
![2022-09-26_16-00_1](https://user-images.githubusercontent.com/33763786/192299330-04bd0b64-afeb-471b-a916-1ecbb49acbdc.png)
![2022-09-26_16-00](https://user-images.githubusercontent.com/33763786/192299339-8af43890-df95-4e97-9431-47daaac9bed5.png)
![2022-09-26_16-15](https://user-images.githubusercontent.com/33763786/192299611-e3e4f200-7ae9-4e80-be2a-07ff36ba96e1.png)

**Nextcloud Files test :** 
![2022-09-27_15-35](https://user-images.githubusercontent.com/33763786/192541067-0407c78f-ba55-4cb6-b591-948d8f06bfb1.png)
![2022-09-26_15-57_1](https://user-images.githubusercontent.com/33763786/192299804-64455a8c-6907-4cdf-97ad-87ae7e12932b.png)
![2022-09-26_15-57](https://user-images.githubusercontent.com/33763786/192299822-300979a5-e90e-4700-930b-17ef57236a69.png)
![2022-09-26_15-56](https://user-images.githubusercontent.com/33763786/192299847-18a15fbc-76c5-4b8a-a3fe-3760a7910d03.png)

**Note :** 
My only point of hesitation concerns the management of long (or even very long) unbreakable words with the "hyphens" CSS property, which sometimes causes a hyphen to appear just above the suspension points.

2023-06-07 12:05 UTC, raimund-schluessler commented
> "npm run cypress:update-snapshots" ran successfully, but Cypress / Runner 1 (and 2) still crash. Don't know why.

https://github.com/nextcloud/nextcloud-vue/pull/3295#issuecomment-1580571620

2023-06-07 12:05 UTC, raimund-schluessler commented
> "npm run cypress:update-snapshots" ran successfully, but Cypress / Runner 1 (and 2) still crash. Don't know why.

You need to download and commit the snapshots that the Github action created: https://github.com/nextcloud/nextcloud-vue/suites/13434227827/artifacts/736443982

2023-06-07 13:10 UTC, Jerome-Herbinet commented
> > "npm run cypress:update-snapshots" ran successfully, but Cypress / Runner 1 (and 2) still crash. Don't know why.
> 
> You need to download and commit the snapshots that the Github action created: https://github.com/nextcloud/nextcloud-vue/suites/13434227827/artifacts/736443982

@raimund-schluessler 
I replaced the snapshots files on my local machine but I cannot go further because gitignore is ignoring the cypress folder. What should I do now ? (remove concerned lines in the .gitignore file ?)

2023-06-08 11:33 UTC, jancborchardt requested changes
Note that in the new screenshots all the words are underlined in red by the spellchecker. It is better to take screenshots when you switch the system language to English  - or alternatively add those words to the dictionary. :) (cc @szaimen to whom I mentioned the issue before too)

2023-06-08 11:33 UTC, jancborchardt commented on cypress/snapshots/base/NcAppSidebar/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_image-secondary_button-editable_true.png
Vertical alignment is off here (also before)

2023-06-08 11:33 UTC, jancborchardt commented on cypress/snapshots/base/NcAppSidebar/NcAppSidebar-compact.cy.js/NcAppSidebar.vue-subname_null-starred_false-compact_true-header_image-secondary_none-editable_true.png
Vertical alignment is off here (also before)

2024-01-25 09:17 UTC, Jerome-Herbinet commented
I'm looking to this old PR.
Can somebody help me to understand why so may files have been changed (97) ?

2024-01-25 09:21 UTC, raimund-schluessler commented
> I'm looking to this old PR. Can somebody help me to understand why so may files have been changed (97) ?

Because `NcAppSidebar` is tested by a visual regression test, for which we need base images to compare with. If you visually change `NcAppSidebar`, the base images need to updated as well.
And since there were changes to this component in the meantime, you got conflicts with all these files.

The best would be to rebase to current `master`, ignore all changes to the base images, and create new/updated base images with your adjustments.

2024-01-26 11:10 UTC, Jerome-Herbinet commented
I rebased the branch and add cypress files, but I can't push because I don't have the write rights : 

git remote add upstream-2 https://github.com/nextcloud-libraries/nextcloud-vue.git
jh-arawa@administrateur-ThinkBook-15-G2-ITL:~/Documents/GitHub/nextcloud-vue$ git remote -v
origin	https://github.com/Jerome-Herbinet/nextcloud-vue.git (fetch)
origin	https://github.com/Jerome-Herbinet/nextcloud-vue.git (push)
upstream	https://github.com/nextcloud/nextcloud-vue.git (fetch)
upstream	https://github.com/nextcloud/nextcloud-vue.git (push)
upstream-2	https://github.com/nextcloud-libraries/nextcloud-vue.git (fetch)
upstream-2	https://github.com/nextcloud-libraries/nextcloud-vue.git (push)
jh-arawa@administrateur-ThinkBook-15-G2-ITL:~/Documents/GitHub/nextcloud-vue$ git push upstream-2 Jerome-Herbinet-patch-better-readability-of-long-files-and-events-names 
Username for 'https://github.com': Jerome-Herbinet
Password for 'https://Jerome-Herbinet@github.com': 
remote: Permission to nextcloud-libraries/nextcloud-vue.git denied to Jerome-Herbinet.
fatal: impossible d'accéder à 'https://github.com/nextcloud-libraries/nextcloud-vue.git/' : The requested URL returned error: 403
jh-arawa@administrateur-ThinkBook-15-G2-ITL:~/Documents/GitHub/nextcloud-vue$ git remote add upstream-2 https://github.com/nextcloud-libraries/nextcloud-vue.git

2024-01-31 20:17 UTC, susnux commented
> but I can't push because I don't have the write rights

You need to accept the invitation first (see your mails)

2024-02-02 09:22 UTC, Jerome-Herbinet commented
> > but I can't push because I don't have the write rights
> 
> You need to accept the invitation first (see your mails)

@susnux thanks for that, and I've just accepted to join the organization, but I've still got the same problem when trying to push :'-(

2024-02-02 12:05 UTC, susnux commented
@Jerome-Herbinet can you try again?

2024-02-02 15:11 UTC, Jerome-Herbinet commented
Push + Sign-off OK, but still Cypress problem. I think that in “real world”, long events or file / folder titles appear flawlessly ; what do you think ?

2024-02-02 15:14 UTC, raimund-schluessler commented
You need to download the screenshots from here https://github.com/nextcloud-libraries/nextcloud-vue/actions/runs/7757784050?pr=4194 under the artifacts section and commit them.

2024-02-05 15:20 UTC, zak39 commented
> You need to download the screenshots from here https://github.com/nextcloud-libraries/nextcloud-vue/actions/runs/7757784050?pr=4194 under the artifacts section and commit them.

Hi @raimund-schluessler :wave: 

I'm zak39, coworker of @Jerome-Herbinet .

I followed your instructions, but, I noticed that the `.gitignore` files ignore the snapshots : 

```
# ...

# Cypress files
cypress/videos
cypress/screenshots
cypress/snapshots/actual
cypress/snapshots/diff
cypress/snapshots/base/**/*-base-*
```

If I understood you, we need to download the snapshots and add them in the project from the Jerome's branch, right ?

2024-04-19 09:44 UTC, Jerome-Herbinet commented
Hello, some time has passed since the comment left by my colleague; I don't know if this PR still has a chance of being accepted and merged one day, or are we abandoning this idea (closing the PR)?

2024-04-19 18:04 UTC, ShGKme commented
I like the idea, especially on a small (but not mobile) screen.

@nextcloud-libraries/developers what do you think?

2024-04-19 19:37 UTC, susnux reviewed
I also like the idea! It is much better as I would expect the title (as an important information) to be visible - especially on the sidebar this is often a problem.

2024-04-22 13:31 UTC, jancborchardt commented
@Jerome-Herbinet my point from above still seems to be current: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4194#pullrequestreview-1469703073

> Note that in the new screenshots all the words are underlined in red by the spellchecker. It is better to take screenshots when you switch the system language to English - or alternatively add those words to the dictionary. :)

2024-04-26 09:39 UTC, Jerome-Herbinet commented
> @Jerome-Herbinet my point from above still seems to be current: [#4194 (review)](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4194#pullrequestreview-1469703073)
> 
> > Note that in the new screenshots all the words are underlined in red by the spellchecker. It is better to take screenshots when you switch the system language to English - or alternatively add those words to the dictionary. :)

Hi @jancborchardt,
I may understand if the text was in French, but it's currently in English (and I don't understand why it's underlined in red by the spellchecker).

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/33763786/4c29729b-ec5e-47e5-9e17-26daf4aaf404)

One more problem : I constantly have conflicts. I tried to delete my branch, and I still get conflicts. 

```
git pull origin Jerome-Herbinet-patch-better-readability-of-long-files-and-events-names
Depuis https://github.com/Jerome-Herbinet/nextcloud-vue
 * branch              Jerome-Herbinet-patch-better-readability-of-long-files-and-events-names -> FETCH_HEAD
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_none-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_none-secondary_none-editable_false.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_none-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_none-secondary_button-editable_false.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_image-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_image-secondary_none-editable_false.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_image-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_true-compact_false-header_image-secondary_button-editable_false.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_none-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_none-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_image-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_null-compact_false-header_image-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_none-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_none-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_image-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_true-starred_false-compact_false-header_image-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_none-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_none-secondary_none-editable_false.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_none-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_none-secondary_button-editable_false.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_image-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_image-secondary_none-editable_false.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_image-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_true-compact_false-header_image-secondary_button-editable_false.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_none-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_none-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_image-secondary_none-editable_true.png (HEAD vs. 90400c11 (chore: Update cypress snapshots))
warning: Cannot merge binary files: cypress/snapshots/base/NcAppSidebar/NcAppSidebar.cy.js/NcAppSidebar.vue-subname_null-starred_null-compact_false-header_image-secondary_button-editable_true.png (HEAD vs. 90400c11 (chore: [...]

2024-05-02 08:04 UTC, ShGKme commented
> @Jerome-Herbinet my point from above still seems to be current: [#4194 (review)](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4194#pullrequestreview-1469703073)
> 
> > Note that in the new screenshots all the words are underlined in red by the spellchecker. It is better to take screenshots when you switch the system language to English - or alternatively add those words to the dictionary. :)

@jancborchardt Working with our screenshot testing in the sidebar is a bit painful. If everything is fine design wise, I can upload correct screenshots.

2024-05-02 17:34 UTC, jancborchardt commented
@ShGKme yep, design is all good, only the red underline of words in the screenshots was/is an issue. :)

2024-05-05 11:19 UTC, ShGKme commented
2 last commits with snapshots are replaced with new snapshots

2024-05-06 15:06 UTC, susnux approved these changes
makes sense for me

2024-05-22 15:04 UTC, Jerome-Herbinet commented
@ShGKme ; can you help me with new conflicts ?

2024-08-22 13:12 UTC, Jerome-Herbinet commented
@jancborchardt after testing NC 29 (should be the same with NC 30) : 
- Files : problem solved with a tooltip (hover)
- Calendar : problem solved with something like I did in this PR

I close this PR

2024-08-22 13:12 UTC, closed without merging