Stop propagation of keyboard navigation in a number of components
nextcloud-libraries/nextcloud-vue pull request #4501
Opened 2023-09-04 13:10 UTC by ShGKme

### ☑️ Resolves

* Fix #

Arrows and <kbd>ESC</kbd> are used for keyboard navigation in some components. But the keydown event is not stopped. As a result, arrows and <kbd>ESC</kbd> not only manipulate such components but also are handled globally.

For example:
- `NcModal`:
  - `ESC` in the open emoji picker or select inside `NcModal` should only close popover, but also close the Modal
  - `Arrows` in Tabs should only switch tabs but also switch slides in `NcModal`

To test add a global event listener:
```js
window.addEventListener('keydown', console.log)
```

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 Tasks

- [x] Add more items to example of `NcModal`
- [x] Simply add `.stop` modifier:
  - `NcAppSidebar`
    - [x] Stop propagation on <kbd>ESC</kbd> on title edit with `nameEditable`
  - `NcAppSidebarTabs`
    - [x] Stop propagation of all keyboard navigation: <kbd>ESC</kbd>, <kbd>↓ ↑ → ←</kbd>
  - `NcInputConfirmCancel`
    - [x] Stop propagation on <kbd>ESC</kbd>
- [x] `NcSelect`: add interceptor via `mapKeydown` to stop propagation when select is open
- [x] `NcPopover`: manually add keydown event listener similar to how focus trap is added. It can be cleaner with an additional wrapper of popover content
  - It also fixes components, based on `NcPopover`:
    - `NcActions`
    - `NcEmojiPicker`
    - `NcUserBubble`
    - `NcColorPicker`
    - `NcDatetimePicker`
    
Ignored:
- NcHeaderMenu:
  - Global ESC handler. Not be a problem, it is never used inside modal and etc.
- NcListItem:
  - hide actions on esc when foducsed

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable

2023-09-06 15:28 UTC, skjnldsv approved these changes

2023-09-06 23:01 UTC, Pytal requested changes

2023-09-06 23:01 UTC, Pytal commented on src/components/NcSelect/NcSelect.vue
> +		patchedKeydownHandler(map, vm) {
Move into props to allow dev override as with the existing props

2023-09-07 15:16 UTC, GretaD commented
you can Dissmiss changes requested by pytal, if its delivered and they dont review it on time

2023-09-07 15:38 UTC, Pytal approved these changes

2023-09-07 15:57 UTC, ShGKme commented
Rebased onto master with fixtup, no other changes

2023-09-07 15:59 UTC, merged