fix checkbox sizing
nextcloud-libraries/nextcloud-vue pull request #4760
Opened 2023-11-06 10:23 UTC by szaimen

Fix https://github.com/nextcloud/server/issues/41262

| Before | After |
|---|---|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/1ac55320-7bf7-46e9-b3cf-64d38c985530) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/f89dc0db-664e-4ccc-94c8-0750851648f7) |

2023-11-06 15:06 UTC, JuliaKirschenheuter approved these changes
😊

2023-11-06 16:01 UTC, raimund-schluessler requested changes
This breaks the height of `NcCheckBoxRadioSwitch` which should be 44 px:

Before:

![Screenshot 2023-11-06 at 16-59-58 Nextcloud Vue Style Guide](https://github.com/nextcloud-libraries/nextcloud-vue/assets/2496460/fbd3e9cc-8695-4ec3-82e1-41624bdac3c8)
After:
![Screenshot 2023-11-06 at 17-00-19 Nextcloud Vue Style Guide](https://github.com/nextcloud-libraries/nextcloud-vue/assets/2496460/844d34ae-58de-4dcd-ab20-f371b5b6b556)

2023-11-07 10:34 UTC, susnux approved these changes

2023-11-07 13:29 UTC, susnux commented on src/components/NcCheckboxRadioSwitch/NcCheckboxContent.vue
> +	box-sizing: content-box !important;
Not sure if this is the best solution, we could also set `min-width: $clickable-area;` and set the padding to `padding: 4px 10px`. That would not require an `!important`.

2023-11-16 14:20 UTC, szaimen commented
Ready for re-review 👍

2023-11-16 14:26 UTC, susnux approved these changes

2023-11-16 14:27 UTC, susnux commented
But please squash the commits

2023-11-16 14:30 UTC, szaimen commented
> But please squash the commits

Can you do that please? I currently cannot check out the vue library at all due to
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/6568d92b-e3e2-4745-b35b-b4de8a3c213d)

2023-11-16 14:31 UTC, JuliaKirschenheuter reviewed
Is it known that checkbox i moved to left now? Or another issue?

![Screenshot from 2023-11-16 15-30-08](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/326725c9-e59f-4bea-bd64-1788927eee32)

2023-11-16 14:38 UTC, JuliaKirschenheuter commented
master:

![Screenshot from 2023-11-16 15-38-28](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/c15a8dea-ff58-4e73-ad0e-d063f8ad58cf)

2023-11-16 15:13 UTC, raimund-schluessler commented
> > But please squash the commits
> 
> Can you do that please? I currently cannot check out the vue library at all due to ![image](https://user-images.githubusercontent.com/42591237/283486610-6568d92b-e3e2-4745-b35b-b4de8a3c213d.png)

Although unrelated to this PR: These files should not be there. I removed them in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4837.

2023-11-17 09:33 UTC, szaimen commented
> But please squash the commits

done 👍

2023-11-17 09:34 UTC, merged

2023-11-30 12:33 UTC, Antreesy commented
Label text is now falling out of the flex container borders:
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/381ca21d-5971-416e-8302-2239bc2d99ca)
With flex-shrink reverted for `checkbox-content__text` class:
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/158cffd8-ff72-4c4a-ae2d-cbcbc7673d77)