Enh/Align app navigation item counter in a better way
nextcloud-libraries/nextcloud-vue pull request #4991
Opened 2023-12-23 12:45 UTC by GVodyanov

### ☑️ Resolves

* Fix https://github.com/nextcloud/mail/issues/9109
* Instead of https://github.com/nextcloud/mail/pull/9179

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/76647797/273ec634-4488-4302-9cc7-e18f61f6edb5) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/76647797/924e9ee5-b732-4f35-bb95-3bb3b81a5089)

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable

2023-12-23 15:35 UTC, susnux submitted a review, later dismissed

2023-12-23 15:35 UTC, susnux commented on src/components/NcAppNavigationItem/NcAppNavigationItem.vue
> +					:class="{'app-navigation-entry__utils--display-actions': forceDisplayActions || menuOpenLocalValue || menuOpen, 'app-navigation-entry__utils--add-spacing': !hasChildren }">
Maybe call it `--has-children` or something? Just to make it more descriptive?

2023-12-23 16:45 UTC, raimund-schluessler requested changes
This leads to the misalignment of the utils/actions on the right, as can be seen in the screenshot. This needs to be fixed, as it looks far worse than the right-aligned counter in my opinion.

2024-01-09 18:36 UTC, GVodyanov commented
@raimund-schluessler Does this look better?
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/76647797/39df9622-b8bd-48a4-b59e-2b6aab9e9efb)

2024-01-11 08:41 UTC, raimund-schluessler commented
> @raimund-schluessler Does this look better? 

Yes, better. But now the counter jumps to the right when the entry is hovered:

![grafik](https://github.com/nextcloud-libraries/nextcloud-vue/assets/2496460/f993a5a0-d8c8-4a67-a0de-0d2ff53b1208)

2024-01-22 15:02 UTC, GVodyanov commented
> > @raimund-schluessler Does this look better?
> 
> Yes, better. But now the counter jumps to the right when the entry is hovered:
> 
> ![grafik](https://private-user-images.githubusercontent.com/2496460/295847190-f993a5a0-d8c8-4a67-a0de-0d2ff53b1208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzUxMjEsIm5iZiI6MTcwNTkzNDgyMSwicGF0aCI6Ii8yNDk2NDYwLzI5NTg0NzE5MC1mOTkzYTVhMC1kOGM4LTRhNjctYTBkZS0wZDJmZjUzYjEyMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTQ0NzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQwMDhkOTUxNWE4MmVmYmY2ZWJkZWIzODYyNjRhZjM5MGZlYmI3Nzg4NDIzMzA3MGMzYjBiZDExNGUyYmQ0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vLIZA_zvLD98k1m6GwC-7023CTdwHFrYf_T0vQRgiQQ)

Could you please suggest how I could reproduce this?

2024-01-22 15:13 UTC, raimund-schluessler commented
> Could you please suggest how I could reproduce this?

Go to the docs https://deploy-preview-4991--nextcloud-vue-components.netlify.app/#/Components/App%20containers/NcAppNavigation?id=ncappnavigationitem scroll to "Element with counter" and hover it.

2024-09-16 09:05 UTC, GVodyanov commented
Fixed in https://github.com/nextcloud-libraries/nextcloud-vue/pull/6054

2024-09-16 09:05 UTC, closed without merging