fix(NcAppNav): changed h2 to span
nextcloud-libraries/nextcloud-vue pull request #5020
Opened 2024-01-02 18:13 UTC by emoral435

### ☑️ Resolves

* Fix #42554

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![293754098-54ff5621-bb32-40f8-bdbe-a05b764b005f](https://github.com/nextcloud-libraries/nextcloud-vue/assets/110193237/e1d7db0b-c701-43c1-bf4d-b1555a1f3238) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/110193237/23f1829f-a999-482f-8f37-b9b4364afc49)

### 🚧 Summary

Change the h2 element in NcAppNavigationCaption to span, as the former h2 element broke the hierarchy of headings within the user page.

### 🏁 Checklist

- [x] ⛑️ Tests are included or are not applicable (NA)
- [x] 📘 Component documentation has been extended, updated or is not applicable (NA)

2024-01-02 18:34 UTC, ShGKme requested changes
It also changes styles (margin)

2024-01-02 22:15 UTC, emoral435 commented
I see what you mean - nice catch! The span needs to have 12px of margins on the bottom for it to be the exact same

h2 | span
---|---
![firefox_k9f0jORbog](https://github.com/nextcloud-libraries/nextcloud-vue/assets/110193237/a774a46b-5c18-4933-ba6f-1b975644ba0f) | ![firefox_SvArjhQGvu](https://github.com/nextcloud-libraries/nextcloud-vue/assets/110193237/ec8a2040-b7ef-435f-b5be-f7bd29f56d90)

newest commit has this change correct, thank you!

2024-01-03 23:48 UTC, Pytal approved these changes

2024-01-04 16:24 UTC, ShGKme approved these changes

2024-01-04 16:37 UTC, JuliaKirschenheuter approved these changes

2024-01-04 16:57 UTC, merged