fix: regression in list item's extra slot
nextcloud-libraries/nextcloud-vue pull request #5250
Opened 2024-02-15 10:29 UTC by hamza221

### ☑️ Resolves

- Fix https://github.com/nextcloud/mail/issues/9334

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
<img width="307" alt="image" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/40746210/326d531e-8a58-48bc-a413-9efb99c05718"> | <img width="307" alt="image" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/40746210/e1e9588e-1e81-4a0c-a693-45611b67cef7">

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

2024-02-15 10:30 UTC, hamza221 commented
cc @GretaD  @susnux @ShGKme

2024-02-15 12:20 UTC, susnux commented
The "after" image also looks broken, for the `NcListItem` I would only expect two lines of text working and the tags to be shown on the very right.

2024-02-15 12:35 UTC, hamza221 commented
> The "after" image also looks broken,

Yes the after is still a bit broken, the tags should be aligned with the lines
This is how it looks on nc.cloud
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/40746210/520f8c7b-9c3a-4592-bcfc-581a65a94022)

> for the `NcListItem` I would only expect two lines of text working and the tags to be shown on the very right.

Isn't the extra slot supposed to show elements below the lines

2024-02-15 13:33 UTC, GretaD commented
> > The "after" image also looks broken,
> 
> Yes the after is still a bit broken, the tags should be aligned with the lines This is how it looks on nc.cloud ![image](https://private-user-images.githubusercontent.com/40746210/305073582-520f8c7b-9c3a-4592-bcfc-581a65a94022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDQyNTEsIm5iZiI6MTcwODAwMzk1MSwicGF0aCI6Ii80MDc0NjIxMC8zMDUwNzM1ODItNTIwZjhjN2ItOWMzYS00NTkyLWJjZmMtNTgxYTY1YTk0MDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDEzMzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZWRjYTA0MjNkYjhhNjYyNjcwNDJjMjljZTk3NWJhNWZiZmM1ZWI5Mzg1NzNiNmMzNTZlZmE3YTAxN2NjYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqRAIiLPg8ES6LLoX0ixVNSWymEMDgblEsm7S8PdQjI)
> 
> > for the `NcListItem` I would only expect two lines of text working and the tags to be shown on the very right.
> 
> Isn't the extra slot supposed to show elements below the lines

this is fixed on mail side, i already pushed a pr for that https://github.com/nextcloud/mail/pull/9336

2024-02-16 18:26 UTC, susnux requested changes
This changes reverting a11y fixes and are not valid -> must not be done. You have to find a solution with the actions outside the anchor element

2024-02-16 18:26 UTC, susnux commented on src/components/NcListItem/NcListItem.vue
> +					<!-- Actions -->
This **must not** be done! An interactive element (the `a`) must **not** contain any other interactive element (the `NcActions`).
We changed this just a couple of weeks ago.

2024-02-18 16:58 UTC, susnux commented
I mean if it fits in the component fine, but we can not have nested interactive elements. This only works with some specific focus handling (e.g. how menu bars work, you can tab the first element but next tab will be outside the menu bar, you then need to use arrows to change focus).

2024-06-05 11:37 UTC, GretaD commented
Hello @susnux, this is still an issue on mail, i would get @jancborchardt @marcoambrosini @nimishavijay involved, what would be a good compromise :)

If it was up to me, I would keep it on the right side, with the argument, that its like this since couple of months and nobody complained about the space, which means that either people are fine with it, or its not used at all :), the tagging is only visual - you cannot filter a certain tag and now that we have different layouts, people can always choose a layout where the list is wide. But, of course, i would be fine to work on another solution.

2024-06-05 15:35 UTC, marcoambrosini commented
> An interactive element (the a) must not contain any other interactive element (the NcActions).

Are you sure that this is the case @susnux afaik an A cannot contain another A but it can contain buttons

2024-06-05 17:31 UTC, ShGKme commented
> e.g. most cards in card layouts

In valid implementation, they are not wrapped in `<a>`. They have a link inside and either use custom `onclick` (like we do in Files) or stretch the link in a pseudo element (like we do in Apps list).

But in both HTML validity and accessibility having nested interactive elements is not valid.

2024-06-05 17:33 UTC, ShGKme commented
See: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5198

2024-06-18 11:20 UTC, GretaD commented
thank you for all the feedback,

@marcoambrosini how should we proceed then?

2024-06-18 11:49 UTC, marcoambrosini commented
I donn't know which would be the better approach. cc @ShGKme and @susnux

2024-07-22 14:40 UTC, hamza221 commented
what we're trying to accomplish is just a third line for 'non interactive- non clickable "tags" ' would that be acceptable ? 
So move the slot outside the NcActions  rename it (thirdline? ) ?

2025-06-05 10:32 UTC, closed without merging