fix sidebar animation glitch
nextcloud-libraries/nextcloud-vue pull request #5389
Opened 2024-03-11 00:08 UTC by RayBB

Signed-off-by: RayBB <RayBB@users.noreply.github.com>

### ☑️ Resolves

- Fix #…

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 Tasks

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [ ] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

2024-03-12 22:09 UTC, ShGKme approved these changes
Very cool, thanks!

Slowed down to better see the difference: 
Before | After
---|---
![Before](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/8703edc6-35bd-41b1-b7ad-d183caf37397) | ![after](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/0b2041c1-5ce4-4496-9ede-208c79496993)

This could be a little bit slower than before in performance, because it causes animation is width change of the main content, triggering resize observers. But should be fine, `NcAppSidebar` does similar change.

If this accurse bad for performance, we can make it absolute during animation:

![Alternative](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/7771a261-eb90-4d6a-a465-4428c7c6b911)

2024-03-12 22:10 UTC, ShGKme commented
/backport to next

2024-03-14 07:28 UTC, skjnldsv commented
Please also check this works on very narrow screens like mobile at 320/400px

2024-03-14 22:00 UTC, ShGKme requested changes

2024-03-14 22:00 UTC, ShGKme commented on src/components/NcAppNavigation/NcAppNavigation.vue
> +		margin-left: -$navigation-width;
On mobile width can be smaller, for example, ~260px on 320px window size.

So margin here should be set the same as on navigation width - using `max` between 300px and `100vw - (var(--app-navigation-padding) ...` (see line 240).

2024-03-20 00:14 UTC, RayBB commented
@ShGKme I updated to fix this for the mobile case.

<details>
  <summary>What master looks like now on small screens</summary>
  
  

https://github.com/nextcloud-libraries/nextcloud-vue/assets/921217/1aff36f7-26f4-4e79-9e04-3814f469ea7b


  
</details> 


<details>
  <summary>And here is what it looks like desktop/mobile with my current changes.</summary>
  
  

https://github.com/nextcloud-libraries/nextcloud-vue/assets/921217/dd2b0f22-a842-42c9-a571-296ff921b3a7


  
</details> 

Please let me know if I should change anything else. Cleaning up commits now.

2024-03-20 01:05 UTC, ShGKme approved these changes
Great

2024-03-20 01:11 UTC, susnux approved these changes

2024-03-20 12:45 UTC, merged

2024-03-20 12:45 UTC, susnux commented
/backport to next