release: v8.11.2
nextcloud-libraries/nextcloud-vue pull request #5462
Opened 2024-04-09 13:59 UTC by Antreesy

## [v8.11.2](https://github.com/nextcloud-libraries/nextcloud-vue/tree/v8.11.2) (2024-04-09)
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-vue/compare/v8.11.1...v8.11.2)

## What's Changed
### 🐛 Fixed bugs
* fix(NcBreadcrumbs): Only render existing hidden breadcrumbs by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5441
* fix(NcAppNavigationItem): Fix uncollapsible entry by @Pytal in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5456
* fix(NcRichText): include all label items by @DorraJaouad in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5455
* fix(sidebar): propagate keydown unless mobile by @pulsejet in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5451
* fix(NcActions): Show last action entry only partial to make it discoverable by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5448
* fix(NcDialog): Set font size to make dialog compatible with Nextcloud 30 by @susnux in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5463
* fix(NcRichText): more strictly resolve vue router's path by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5419
* fix(NcAvatar): support in-app router links for contact menu by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5477
### Other Changes
* Updates for project Nextcloud vue library by @transifex-integration in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5447
* Updates for project Nextcloud vue library by @transifex-integration in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5478

## New Contributors
* @DorraJaouad made their first contribution in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5455

2024-04-09 14:01 UTC, emoral435 approved these changes

2024-04-09 14:11 UTC, Antreesy commented
Waiting for author inputs to also include:
- https://github.com/nextcloud-libraries/nextcloud-vue/pull/5448
- https://github.com/nextcloud-libraries/nextcloud-vue/pull/5419
- https://github.com/nextcloud-libraries/nextcloud-vue/pull/5451

2024-04-09 21:04 UTC, susnux requested changes

2024-04-09 21:04 UTC, susnux commented on CHANGELOG.md
> +### 🐛 Fixed bugs
Update the changelog, then it should be good to go

2024-04-10 13:11 UTC, ShGKme commented
- https://github.com/nextcloud-libraries/nextcloud-vue/pull/5477
- 👉👈

2024-04-10 14:55 UTC, ShGKme approved these changes

2024-04-10 15:05 UTC, merged