fix(NcDateTime): Respect language
nextcloud-libraries/nextcloud-vue pull request #5501
Opened 2024-04-17 17:52 UTC by Pytal

### ☑️ Resolves

- Fix https://github.com/nextcloud/server/issues/15457

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/24800714/6091a8fe-6a9b-43fb-ac43-82df80fe1fa2) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/24800714/d09e9510-1887-4be9-b184-603a0b14ea8e)

### 🏁 Checklist

- [ ] ⛑️ Tests are included or are not applicable
- [x] 📘 Component documentation has been extended, updated or is not applicable
- [ ] 3️⃣ Backport to `next` requested with a Vue 3 upgrade

2024-04-17 18:05 UTC, Pytal commented
/backport to next

2024-04-17 23:08 UTC, susnux requested changes
This does not work, for example I have configured Nextcloud to use English (US) lanuage, but German locale (I want 24h system and dd.mm.yyyy days but English texts).
Now also english

2024-04-17 23:08 UTC, susnux commented on src/composables/useFormatDateTime.js
> +		const formatter = new Intl.DateTimeFormat(getLanguage(), wrappedOptions.value.format)
This does not work, for example I have configured Nextcloud to use English (US) lanuage, but German locale (I want 24h system and dd.mm.yyyy days but English texts).
Now I receive 12h times and English date format.

2024-04-17 23:12 UTC, susnux commented on src/composables/useFormatDateTime.js
> +		const formatter = new Intl.DateTimeFormat(getLanguage(), wrappedOptions.value.format)
So at least the full formatted time needs to use the users **locale** not language

2024-04-17 23:13 UTC, susnux commented on src/composables/useFormatDateTime.js
> +			const formatter = new Intl.RelativeTimeFormat(getLanguage(), { numeric: 'auto', style: wrappedOptions.value.relativeTime })
This is ok as this only is used for relative time which should be independent from **locale** and only depend on **lanuage**

2024-04-19 19:40 UTC, susnux approved these changes
:+1:

2024-04-19 19:51 UTC, ShGKme approved these changes

2024-04-19 19:51 UTC, ShGKme commented on tests/unit/components/NcDateTime/NcDateTime.spec.js
> +		it('', () => {
Test description is missing

2024-04-19 19:51 UTC, ShGKme commented on tests/unit/components/NcDateTime/NcDateTime.spec.js
> +			expect(wrapper.element.textContent).toMatch('gestern')
```suggestion
			expect(wrapper.text()).toMatch('gestern')
```

2024-04-22 20:49 UTC, susnux commented
@Pytal conflicts + maybe include Grigoriis comments :)

2024-04-22 23:46 UTC, merged