Reduce input border width
nextcloud-libraries/nextcloud-vue pull request #5563
Opened 2024-05-07 14:57 UTC by marcoambrosini

https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/a2c1e554-3488-4d99-8b82-a3c377f768ab

2024-05-07 14:59 UTC, ShGKme commented
> Waiting for server `border-width` variable to be in before merging this

Can you link the PR? I cannot find it...

2024-05-07 15:00 UTC, marcoambrosini commented
@ShGKme it doesn't exist yet :)

2024-05-07 15:00 UTC, jancborchardt requested changes
The input field looks good, but for the textarea, it jumps around vertically on focus, a result of the 1px/2px change on focus.

(And yes, waiting for server for the --border-width variable.)

2024-05-10 07:48 UTC, marcoambrosini commented
variable here https://github.com/nextcloud/server/pull/45247/commits/43510be0343aaedce183950e7a4a555951ec00aa

2024-05-13 13:16 UTC, ShGKme reviewed
For compatibility with older server, we probably should use 2px as a fallback

2024-05-13 13:16 UTC, ShGKme commented on src/components/NcInputField/NcInputField.vue
> +		border: var(--border-width-input) solid var(--color-border-maxcontrast);
```suggestion
		border: var(--border-width-input, 2px) solid var(--color-border-maxcontrast);
```

2024-05-13 13:16 UTC, ShGKme commented on src/components/NcInputField/NcInputField.vue
> +		border: var(--border-width-input) solid var(--color-border-maxcontrast);
And the same in other places

2024-05-16 13:40 UTC, marcoambrosini commented
@ShGKme I've switched back to borders, but there's still a problem with the text jumping inside on hover and focus. I've tried to change the paddings but the problem is still there. Could you please have a look?

2024-05-17 09:53 UTC, susnux approved these changes

2024-05-31 12:11 UTC, szaimen approved these changes
🐘

2024-05-31 12:11 UTC, merged

2024-05-31 12:37 UTC, marcoambrosini commented
/backport to next

2024-05-31 15:09 UTC, ShGKme commented
> but there's still a problem with the text jumping inside on hover and focus

Was it resolved?