Fix list-item layout regressions
nextcloud-libraries/nextcloud-vue pull request #5775
Opened 2024-07-04 06:41 UTC by marcoambrosini

## Clickable area @34px
<img width="1015" alt="Screenshot 2024-07-04 at 08 36 27" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/8f9f89cb-f6b4-4380-afa5-a09d5cfae256">
<img width="1048" alt="Screenshot 2024-07-04 at 08 40 27" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/827b23b8-f750-4335-a34e-e700cd70bd59">

## Clickable area @44px
<img width="1015" alt="Screenshot 2024-07-04 at 08 37 23" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/025769a2-ae82-4258-8ae9-f3716b77aa62">
<img width="1048" alt="Screenshot 2024-07-04 at 08 40 43" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/e69a51b8-d496-430c-986c-95503b777427">

2024-07-04 14:19 UTC, hamza221 approved these changes

2024-07-04 14:52 UTC, susnux commented on src/components/NcListItem/NcListItem.vue
> +	margin: 2px;
Comment makes no sense then anymore.
Also does this change the look on stable29?

2024-07-04 14:53 UTC, susnux commented on src/components/NcListItem/NcListItem.vue
> +		justify-content: center;
how is this related?

2024-07-04 14:57 UTC, susnux commented on src/components/NcListItem/NcListItem.vue
> +		justify-content: center;
This makes the component jump if there is a `extra` added while there was already `details`.
E.g. adding a "unread" notification bubble icon will now make it jump a lot.

2024-07-04 15:03 UTC, susnux requested changes
This introduces jumping behavior

2024-07-09 12:05 UTC, jancborchardt reviewed
@marcoambrosini will this also fix the inconsistent spacing and sizing between the button and the entries in the navigation? See here, especially the size difference, and left and right margin:
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/925062/b0620edc-d95e-43ad-a9d9-47e2f85f6875)

2024-07-16 08:44 UTC, marcoambrosini commented
@jancborchardt no this is unrelated to that

2024-07-16 08:45 UTC, marcoambrosini commented
@susnux you did a better fix for this right?

2024-07-18 13:58 UTC, marcoambrosini commented
close in favor of [#list](https://github.com/nextcloud-libraries/nextcloud-vue/pull/5780#pullrequestreview-2185912459)

2024-07-18 13:58 UTC, closed without merging